#include"my_8_bit.h"

int main(){
	Program EUCLALG;
	EUCLALG.PRINT("OUTPUT: ");
	//INPUT FOR NUMBER A
	EUCLALG.SCANCH();
	EUCLALG.NOP();
	EUCLALG.LSLOAD(R14,R1);
	EUCLALG.LSLOAD(R1,R1);
	EUCLALG.LSLOAD(R1,R1);
	EUCLALG.LSLOAD(R1,R1);
	//EUCLALG.LOADLIT(R14, "00");
	EUCLALG.SCANCH();
	EUCLALG.NOP();
	EUCLALG.ADD(R1,R14,R1);
	//EUCLALG.HEX2ASC(R1,R0);
	//EUCLALG.PRINTCH(R0);
	//EUCLALG.NOP();
	//EUCLALG.LSLOAD(R1,R0);
	//EUCLALG.LSLOAD(R1,R0);
	//EUCLALG.LSLOAD(R1,R0);
	//EUCLALG.LSLOAD(R1,R0);
	//EUCLALG.HEX2ASC(R0,R0);
	//EUCLALG.PRINTCH(R0);
	//EUCLALG.NOP();
	
	//INPUT FOR NUMBER B
	EUCLALG.SCANCH();
	EUCLALG.NOP();
	EUCLALG.LSLOAD(R14,R2);
	EUCLALG.LSLOAD(R2,R2);
	EUCLALG.LSLOAD(R2,R2);
	EUCLALG.LSLOAD(R2,R2);
	//EUCLALG.LOADLIT(R14, "00");
	EUCLALG.SCANCH();
	EUCLALG.NOP();
	EUCLALG.ADD(R2,R14,R2);
	//EUCLALG.HEX2ASC(R2,R0);
	//EUCLALG.PRINTCH(R0);
	//EUCLALG.NOP();
	//EUCLALG.LSLOAD(R2,R0);
	//EUCLALG.LSLOAD(R2,R0);
	//EUCLALG.LSLOAD(R2,R0);
	//EUCLALG.LSLOAD(R2,R0);
	//EUCLALG.HEX2ASC(R0,R0);
	//EUCLALG.PRINTCH(R0);
	//EUCLALG.NOP();
	EUCLALG.SUB(R1,R2,R3);
	EUCLALG.BRN("0002");
	EUCLALG.COPY(R3,R1);
	EUCLALG.MJMP("0004");
	EUCLALG.COPY(R1,R4);
	EUCLALG.COPY(R2,R1);
	EUCLALG.COPY(R4,R2);
	EUCLALG.LOADLIT(R3,"00");
	EUCLALG.SUB(R2,R3,R3);
	//EUCLALG.NOP();
	EUCLALG.BRE("0001");
	EUCLALG.MJMP("000b");	
	EUCLALG.LOADLIT(R10,"00");
	EUCLALG.STORE(R1,R10);
	EUCLALG.HEX2ASC(R1,R0);
	EUCLALG.PRINTCH(R0);
	EUCLALG.NOP();
	EUCLALG.LSLOAD(R1,R1);
	EUCLALG.LSLOAD(R1,R1);
	EUCLALG.LSLOAD(R1,R1);
	EUCLALG.LSLOAD(R1,R1);
	EUCLALG.HEX2ASC(R1,R0);
	EUCLALG.NOP();
	EUCLALG.PRINTCH(R0);
	EUCLALG.PRINT(" ");
	EUCLALG.PRINT(" FINISH!_");
	EUCLALG.NOP();
	EUCLALG.end();
}
